package com.product.data.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class District {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_district.guid
     *
     * @mbggenerated
     */
    private Integer guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_district.districtId
     *
     * @mbggenerated
     */
    private String districtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_district.districtName
     *
     * @mbggenerated
     */
    private String districtname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_district.cityId
     *
     * @mbggenerated
     */
    private String cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_district.guid
     *
     * @return the value of ec_district.guid
     *
     * @mbggenerated
     */
//    public Integer getGuid() {
//        return guid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_district.guid
     *
     * @param guid the value for ec_district.guid
     *
     * @mbggenerated
     */
//    public void setGuid(Integer guid) {
//        this.guid = guid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_district.districtId
     *
     * @return the value of ec_district.districtId
     *
     * @mbggenerated
     */
//    public String getDistrictid() {
//        return districtid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_district.districtId
     *
     * @param districtid the value for ec_district.districtId
     *
     * @mbggenerated
     */
//    public void setDistrictid(String districtid) {
//        this.districtid = districtid == null ? null : districtid.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_district.districtName
     *
     * @return the value of ec_district.districtName
     *
     * @mbggenerated
     */
//    public String getDistrictname() {
//        return districtname;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_district.districtName
     *
     * @param districtname the value for ec_district.districtName
     *
     * @mbggenerated
     */
//    public void setDistrictname(String districtname) {
//        this.districtname = districtname == null ? null : districtname.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_district.cityId
     *
     * @return the value of ec_district.cityId
     *
     * @mbggenerated
     */
//    public String getCityid() {
//        return cityid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_district.cityId
     *
     * @param cityid the value for ec_district.cityId
     *
     * @mbggenerated
     */
//    public void setCityid(String cityid) {
//        this.cityid = cityid == null ? null : cityid.trim();
//    }
}