package com.product.data.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.log4j.Log4j;

import java.io.Serializable;

@Data
@Log4j
@NoArgsConstructor
@AllArgsConstructor
public class Province implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_province.guid
     *
     * @mbggenerated
     */
    private Integer guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_province.provinceId
     *
     * @mbggenerated
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_province.provinceName
     *
     * @mbggenerated
     */
    private String provincename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_province.guid
     *
     * @return the value of ec_province.guid
     *
     * @mbggenerated
     */
//    public Integer getGuid() {
//        return guid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_province.guid
     *
     * @param guid the value for ec_province.guid
     *
     * @mbggenerated
     */
//    public void setGuid(Integer guid) {
//        this.guid = guid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_province.provinceId
     *
     * @return the value of ec_province.provinceId
     *
     * @mbggenerated
     */
//    public String getProvinceid() {
//        return provinceid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_province.provinceId
     *
     * @param provinceid the value for ec_province.provinceId
     *
     * @mbggenerated
     */
//    public void setProvinceid(String provinceid) {
//        this.provinceid = provinceid == null ? null : provinceid.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_province.provinceName
     *
     * @return the value of ec_province.provinceName
     *
     * @mbggenerated
     */
//    public String getProvincename() {
//        return provincename;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_province.provinceName
     *
     * @param provincename the value for ec_province.provinceName
     *
     * @mbggenerated
     */
//    public void setProvincename(String provincename) {
//        this.provincename = provincename == null ? null : provincename.trim();
//    }
}