package com.product.data.dao;

import com.product.data.pojo.District;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_district
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_district
     *
     * @mbggenerated
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_district
     *
     * @mbggenerated
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_district
     *
     * @mbggenerated
     */
    District selectByPrimaryKey(Integer guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_district
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_district
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(District record);
}